import "./globals.css";
import { Inter } from "next/font/google";
import Menu from "../../components/ui/Nav/Menu";
import Navbar from "../../components/ui/mobileNav.tsx/Nav";
import Footer from "../../components/ui/footer/Footer";

import Hero from "../../components/ui/heroSection/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max margin-nav">
          <Navbar />
        </div>
        {children}
        <div className="max margin">
          <Footer />
        </div>
      </body>
    </html>
  );
}
